# Generated by Django 4.2.4 on 2023-09-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_email_contact_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_info',
            new_name='email',
        ),
    ]
